/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourRouteImport } from './routes/tour'
import { Route as MusicRouteImport } from './routes/music'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BioRouteImport } from './routes/bio'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as DiscographyIndexRouteImport } from './routes/discography.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as DiscographySlugRouteImport } from './routes/discography.$slug'

const TourRoute = TourRouteImport.update({
  id: '/tour',
  path: '/tour',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscographyIndexRoute = DiscographyIndexRouteImport.update({
  id: '/discography/',
  path: '/discography/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscographySlugRoute = DiscographySlugRouteImport.update({
  id: '/discography/$slug',
  path: '/discography/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bio': typeof BioRoute
  '/cart': typeof CartRoute
  '/music': typeof MusicRoute
  '/tour': typeof TourRoute
  '/discography/$slug': typeof DiscographySlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/discography/': typeof DiscographyIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bio': typeof BioRoute
  '/cart': typeof CartRoute
  '/music': typeof MusicRoute
  '/tour': typeof TourRoute
  '/discography/$slug': typeof DiscographySlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/discography': typeof DiscographyIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bio': typeof BioRoute
  '/cart': typeof CartRoute
  '/music': typeof MusicRoute
  '/tour': typeof TourRoute
  '/discography/$slug': typeof DiscographySlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/discography/': typeof DiscographyIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bio'
    | '/cart'
    | '/music'
    | '/tour'
    | '/discography/$slug'
    | '/shop/$slug'
    | '/discography/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bio'
    | '/cart'
    | '/music'
    | '/tour'
    | '/discography/$slug'
    | '/shop/$slug'
    | '/discography'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bio'
    | '/cart'
    | '/music'
    | '/tour'
    | '/discography/$slug'
    | '/shop/$slug'
    | '/discography/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BioRoute: typeof BioRoute
  CartRoute: typeof CartRoute
  MusicRoute: typeof MusicRoute
  TourRoute: typeof TourRoute
  DiscographySlugRoute: typeof DiscographySlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  DiscographyIndexRoute: typeof DiscographyIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tour': {
      id: '/tour'
      path: '/tour'
      fullPath: '/tour'
      preLoaderRoute: typeof TourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discography/': {
      id: '/discography/'
      path: '/discography'
      fullPath: '/discography/'
      preLoaderRoute: typeof DiscographyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discography/$slug': {
      id: '/discography/$slug'
      path: '/discography/$slug'
      fullPath: '/discography/$slug'
      preLoaderRoute: typeof DiscographySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BioRoute: BioRoute,
  CartRoute: CartRoute,
  MusicRoute: MusicRoute,
  TourRoute: TourRoute,
  DiscographySlugRoute: DiscographySlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  DiscographyIndexRoute: DiscographyIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
