// packages/hooks/useOfflineLibrary.ts
//
// Offline-first playback for mobile PWA use. Two moving parts:
//  1. A Workbox-generated service worker (see workbox-config.js below) that
//     caches audio responses with a CacheFirst strategy once fetched.
//  2. An IndexedDB table (via `idb`) that tracks which track ids the user
//     explicitly chose to "download" -- this is a user-facing library list,
//     distinct from whatever the service worker has opportunistically cached.
//
// This intentionally lives entirely client-side. There's no server table
// for "what did this device download" -- it's local storage, per device,
// by design (a phone with 3 albums downloaded shouldn't sync that fact to
// a different phone).

'use client';

import { useCallback, useEffect, useState } from 'react';
import { openDB, type IDBPDatabase } from 'idb';

const DB_NAME = 'musicbox-offline';
const STORE_NAME = 'downloaded-tracks';

interface DownloadedTrack {
  trackId: string;
  title: string;
  cachedAt: number;
}

async function getDb(): Promise<IDBPDatabase> {
  return openDB(DB_NAME, 1, {
    upgrade(db) {
      db.createObjectStore(STORE_NAME, { keyPath: 'trackId' });
    },
  });
}

export function useOfflineLibrary() {
  const [downloaded, setDownloaded] = useState<DownloadedTrack[]>([]);

  const refresh = useCallback(async () => {
    const db = await getDb();
    setDownloaded(await db.getAll(STORE_NAME));
  }, []);

  useEffect(() => {
    // Register the Workbox-built service worker (public/sw.js, generated by
    // workbox-cli from workbox-config.js -- see production-architecture.md).
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js');
    }
    refresh();
  }, [refresh]);

  /** Fetch the track fully (priming the SW's CacheFirst cache) and record it as downloaded. */
  async function downloadTrack(trackId: string, title: string, streamUrl: string) {
    const response = await fetch(streamUrl); // hits the network once; Workbox caches the response
    if (!response.ok) throw new Error(`Failed to download track ${trackId}`);

    const db = await getDb();
    await db.put(STORE_NAME, { trackId, title, cachedAt: Date.now() });
    await refresh();
  }

  async function removeDownload(trackId: string) {
    const db = await getDb();
    await db.delete(STORE_NAME, trackId);
    await refresh();
    // Note: this removes the library entry; evicting the underlying SW
    // cache entry is handled by Workbox's expiration plugin (see config).
  }

  async function isDownloaded(trackId: string): Promise<boolean> {
    const db = await getDb();
    return (await db.get(STORE_NAME, trackId)) != null;
  }

  return { downloaded, downloadTrack, removeDownload, isDownloaded, refresh };
}

// ----------------------------------------------------------------------------
// workbox-config.js (project root, run via `npx workbox generateSW`)
// ----------------------------------------------------------------------------
//
// module.exports = {
//   globDirectory: 'public/',
//   globPatterns: ['**/*.{html,js,css}'],
//   swDest: 'public/sw.js',
//   runtimeCaching: [
//     {
//       urlPattern: ({ url }) => url.pathname.startsWith('/storage/v1/object/'),
//       handler: 'CacheFirst',
//       options: {
//         cacheName: 'audio-cache',
//         expiration: { maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 90 }, // 90 days
//         cacheableResponse: { statuses: [0, 200] },
//         rangeRequests: true, // required for audio seeking while offline
//       },
//     },
//   ],
// };
